import "./banner/banner.js"
import "./dashboard/dashboard.js"
import "./store/store.js"
import "./product/product.js"
import "./feedback/feedback.js"
import "./setting/setting.js"
import "./category/category.js"