import "./custome-table/custome-table.js"
import "./spinner/spinner.js"
import "./empty-data/empty-data.js"
import "./toast/toast.js"
import "./pagination/pagination.js"
import "./badge/badge.js"
import "./modal/modal.js"